/*
 * Copyright 2024-2026 Firefly Software Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.fireflyframework.data.cost;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

import java.time.Instant;
import java.util.Map;

/**
 * Report containing enrichment cost information aggregated by provider.
 *
 * <p>This report provides a breakdown of costs per provider, including
 * call counts and total costs. It is generated by the
 * {@link EnrichmentCostTracker} and exposed via the
 * {@link org.fireflyframework.data.controller.EnrichmentCostController}.</p>
 *
 * <p><b>Example Response:</b></p>
 * <pre>{@code
 * {
 *   "providerCosts": {
 *     "Financial Data Provider": {
 *       "providerName": "Financial Data Provider",
 *       "callCount": 150,
 *       "costPerCall": 0.05,
 *       "totalCost": 7.50
 *     },
 *     "Credit Bureau Provider": {
 *       "providerName": "Credit Bureau Provider",
 *       "callCount": 80,
 *       "costPerCall": 1.50,
 *       "totalCost": 120.00
 *     }
 *   },
 *   "totalCost": 127.50,
 *   "currency": "USD",
 *   "generatedAt": "2026-02-22T10:30:00Z"
 * }
 * }</pre>
 */
@Data
@Builder
@Schema(description = "Enrichment cost report with per-provider breakdown")
public class CostReport {

    @Schema(description = "Cost breakdown by provider name")
    private final Map<String, ProviderCost> providerCosts;

    @Schema(description = "Total cost across all providers", example = "127.50")
    private final double totalCost;

    @Schema(description = "Currency for all costs (ISO 4217)", example = "USD")
    private final String currency;

    @Schema(description = "Timestamp when the report was generated")
    private final Instant generatedAt;

    /**
     * Cost information for a single provider.
     */
    @Data
    @Builder
    @Schema(description = "Cost details for a single enrichment provider")
    public static class ProviderCost {

        @Schema(description = "Name of the provider", example = "Financial Data Provider")
        private final String providerName;

        @Schema(description = "Total number of calls made to this provider", example = "150")
        private final long callCount;

        @Schema(description = "Cost per individual call", example = "0.05")
        private final double costPerCall;

        @Schema(description = "Total cost for this provider (callCount * costPerCall)", example = "7.50")
        private final double totalCost;
    }
}
